#!/usr/bin/env bash
# installs load balancer and sets up round robin scheduling algorithm
STUDENT_ID=324143

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000
    option http-server-close

frontend main
    bind *:80
    default_backend app_servers

backend app_servers
    balance roundrobin
    server ${STUDENT_ID}-web-01 52.206.238.2:80 check
    server ${STUDENT_ID}-web-02 34.229.55.39:80 check
EOF

# Restart HAProxy
sudo service haproxy restart

# Enable HAProxy to be managed via init script
sudo systemctl enable haproxy

# Verify HAProxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
